### ISSUE TITLE
When are dot files created

### ISSUE THREAD

**Issue by underdoeg** [tgfrerer/island#18]
While working on le_video, I noticed that a new .dot file is generated in every frame and spamming the output. is this the intended behaviour or did I somehow change the internal system so it thinks it needs to recreate the viz?

**Comment by tgfrerer** [comment]
Can we make this a discussion rather than an issue please? If I add an answer here, it will disappear as soon as the issue is closed, and I'd rather keep it around in case other folks run into the same isse...

**Comment by tgfrerer** [comment]
I've added an answer under discussions :) 

https://github.com/tgfrerer/island/discussions/20

**Comment by underdoeg** [comment]
Thanks
