### ISSUE TITLE
global le::api in le_log

### ISSUE THREAD

**Issue by underdoeg** [tgfrerer/island#25]
Doesn't this result in an unclear le::api and pollutes the global namespace?

https://github.com/tgfrerer/island/blob/978759ad830ba41a89f8662829ce356e0339eaba/modules/le_log/le_log.h#L45

I guess it should be ```static const auto &log_api              = le_log_api_i;``` or be placed in a le_log namespace

**Comment by tgfrerer** [comment]
yes. good catch! the namespace should be “le_log”  instead of “le”

**Comment by underdoeg** [comment]
yes, but the actual Log class should still be le::Log I think?
