### ISSUE TITLE
problem trying to compile examples

### ISSUE THREAD

**Issue by cyrstem** [tgfrerer/island#29]
hi  im  trying to compile the examples but i get 
433 |  *properties = self->raytracingProperties;
      |                      ^~~~~~~~~~~~~~~~~~~~
[68/74] Building CXX object le_backend_vk/CMakeFiles/le_backend_vk.dir/le_backend_vk.cpp.o
FAILED: le_backend_vk/CMakeFiles/le_backend_vk.dir/le_bac,

**Comment by tgfrerer** [comment]
hi @cyrstem, can it be that your system has a relatively old Vulkan SDK installed? In that case upgrading your SDK will help.

**Comment by cyrstem** [comment]
yup that did the trick haven't updated in a log time 
thanks
