### ISSUE TITLE
An error occurred while running example(hello world and ) on win10.

### ISSUE THREAD

**Issue by Kylewlk** [tgfrerer/island#31]
An error occurred while running example(hello world and ) on win10. Nothing show on window.

The console outputs :

[ le_instance_vk            | INFO    ] Debug instance layers added.
[ le_instance_vk            | INFO    ] Vulkan Validation Layers Active.
[ le_instance_vk            | INFO    ] Instance created.
[ le_backend                | INFO    ] Selected GPU: AMD Radeon R5 430
[ le_backend                | INFO    ] Found versatile queue matching: '{ Graphics }'
[ le_backend                | ERROR   ] No available queue matching requirement: '{ Compute }'
[ le_backend                | INFO    ] Enabled Device Extensions:
[ le_backend                | INFO    ]          + VK_KHR_swapchain
[ le_instance_vk            | INFO    ] vk validation: {   GENERAL |    INFO} Inserted device layer VK_LAYER_KHRONOS_validation (C:\VulkanSDK\1.2.182.0\Bin\.\VkLayer_khronos_validation.dll)
[ le_instance_vk            | INFO    ] vk validation: {   GENERAL |    INFO} Failed to find vkGetDeviceProcAddr in layer C:\WINDOWS\System32\DriverStore\FileRepository\u0364501.inf_amd64_9e2e01a9e583efcd\B364303\.\amdvlk64.dll
[ le_instance_vk            | ERROR   ] vk validation: {   GENERAL |   ERROR} terminator_CreateDevice: Failed in ICD C:\WINDOWS\System32\DriverStore\FileRepository\u0364501.inf_amd64_9e2e01a9e583efcd\B364303\.\amdvlk64.dll vkCreateDevicecall
[ le_instance_vk            | ERROR   ] vk validation: {   GENERAL |   ERROR} vkCreateDevice:  Failed to create device chain.

**Comment by tgfrerer** [comment]
this is probably because the gpu in question does not appear to support a compute queue...
