### ISSUE TITLE
build error VK_MAKE_API_VERSION not declared 

### ISSUE THREAD

**Issue by themancalledjakob** [tgfrerer/island#38]
Compiled with Debian Bullseye (vulkan version 1.2.162). the `ninja` command gives following error:
`island/modules/le_backend_vk/le_instance_vk.cpp:448:30: error: ‘VK_MAKE_API_VERSION’ was not declared in this scope; did you mean ‘VK_MAKE_VERSION’? 448 | .setApplicationVersion( VK_MAKE_API_VERSION( 0, 0, 0, 0 ) ) | ^~~~~~~~~~~~~~~~~~~ | VK_MAKE_VERSION `

Fix in #37 

If you run into this on debian, you can install libvulkan-dev from [backports](https://backports.debian.org/Instructions/) like that:
`sudo apt install libvulkan-dev -t bullseye-backports`

**Comment by tgfrerer** [comment]
fixed via #37

**Comment by tgfrerer** [comment]
Thank you!
